window.ISORA_SIGN_LABELS = {
  assalomu_alaykum: 'Здравствуйте',
  bahor: 'Весна',
  birga: 'Вместе',
  "bo'sh": 'Пусто',
  bosh_kiyim: 'Головной убор',
  boshlanishi: 'Начало',
  bozor: 'Базар',
  eshik: 'Дверь',
  futbol: 'Футбол',
  iltimos: 'Пожалуйста',
  internet: 'Интернет',
  javob: 'Ответ',
  jismoniy_tarbiya: 'Физкультура',
  karam: 'Капуста',
  kartoshka: 'Картофель',
  kichik: 'Маленький',
  kitob: 'Книга',
  "ko'prik": 'Мост',
  likopcha: 'Тарелка',
  maktab: 'Школа',
  mehmonxona: 'Гостиница',
  mehribon: 'Добрый',
  metro: 'Метро',
  musiqa: 'Музыка',
  "o'simlik_yog'i": 'Растительное масло',
  "o'ynash": 'Играть',
  ochish: 'Открыть',
  ot: 'Лошадь',
  ovqat_tayyorlash: 'Готовить еду',
  oxiri: 'Конец',
  poezd: 'Поезд',
  pomidor: 'Помидор',
  qidirish: 'Искать',
  qish: 'Зима',
  "qo'ziqorin": 'Грибы',
  qor: 'Снег',
  "qorong'i": 'Темно',
  quyon: 'Кролик',
  restoran: 'Ресторан',
  "sariyog'": 'Сливочное масло',
  shokolad: 'Шоколад',
  sovun: 'Мыло',
  stakan: 'Стакан',
  televizor: 'Телевизор',
  tosh: 'Камень',
  toza: 'Чисто',
  turish: 'Встать',
  "yomg'ir": 'Дождь',
  yopish: 'Закрыть',
  yordam_berish: 'Помочь'
};

window.isoraSignLabel = (sign) => (
  window.ISORA_SIGN_LABELS[sign] || sign.replaceAll('_', ' ')
);
