window.ISORA_SIGN_LABELS = {
  assalomu_alaykum: 'Assalomu alaykum',
  bahor: 'Bahor',
  birga: 'Birga',
  "bo'sh": "Bo'sh",
  bosh_kiyim: 'Bosh kiyim',
  boshlanishi: 'Boshlanishi',
  bozor: 'Bozor',
  eshik: 'Eshik',
  futbol: 'Futbol',
  iltimos: 'Iltimos',
  internet: 'Internet',
  javob: 'Javob',
  jismoniy_tarbiya: 'Jismoniy tarbiya',
  karam: 'Karam',
  kartoshka: 'Kartoshka',
  kichik: 'Kichik',
  kitob: 'Kitob',
  "ko'prik": "Ko'prik",
  likopcha: 'Likopcha',
  maktab: 'Maktab',
  mehmonxona: 'Mehmonxona',
  mehribon: 'Mehribon',
  metro: 'Metro',
  musiqa: 'Musiqa',
  "o'simlik_yog'i": "O'simlik yog'i",
  "o'ynash": "O'ynash",
  ochish: 'Ochish',
  ot: 'Ot',
  ovqat_tayyorlash: 'Ovqat tayyorlash',
  oxiri: 'Oxiri',
  poezd: 'Poyezd',
  pomidor: 'Pomidor',
  qidirish: 'Qidirish',
  qish: 'Qish',
  "qo'ziqorin": "Qo'ziqorin",
  qor: 'Qor',
  "qorong'i": "Qorong'i",
  quyon: 'Quyon',
  restoran: 'Restoran',
  "sariyog'": "Sariyog'",
  shokolad: 'Shokolad',
  sovun: 'Sovun',
  stakan: 'Stakan',
  televizor: 'Televizor',
  tosh: 'Tosh',
  toza: 'Toza',
  turish: 'Turish',
  "yomg'ir": "Yomg'ir",
  yopish: 'Yopish',
  yordam_berish: 'Yordam berish'
};

window.isoraSignLabel = (sign) => (
  window.ISORA_SIGN_LABELS[sign] || sign.replaceAll('_', ' ')
);
